IMAGE_INSTALL_append = " libuio"
IMAGE_INSTALL_append = " libgpio"
IMAGE_INSTALL_append = " libpwm"
IMAGE_INSTALL_append = " libvrc"
IMAGE_INSTALL_append = " pwmdemo"
IMAGE_INSTALL_append = " gpioutil"
IMAGE_INSTALL_append = " kmsdemo"
